id: IE6477585
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T21:53:52+00:00'
last_modified: '2022-06-08T02:01:34.276246+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19604
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་གཞུང་དོན་རབ་ཏུ་གསལ་བའི་ཉི་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7074':
      image_group_id: I0444
      title: ''
      total_pages: 543
      order: 1
      base_file: 7074.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
