id: P004572
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:42:18.481774
source_metadata:
  id: bdr:W19604
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་གཞུང་དོན་རབ་ཏུ་གསལ་བའི་ཉི་མ།
  author: ''
  volumes:
    1b0c48a30e8c486db20fa2d95f33315e:
      image_group_id: I0444
      title: ''
      volume_number: 1
      total_pages: 543
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
