id: P004572
initial_creation_type: ocr
source_metadata:
  id: bdr:W19604
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་གཞུང་དོན་རབ་ཏུ་གསལ་བའི་ཉི་མ།
  author: ''
  volumes:
    1b0c48a30e8c486db20fa2d95f33315e:
      image_group_id: I0444
      title: ''
      volume_number: 1
      total_pages: 543
